### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by AllyHancock** [AnimaApp/Launchpad#3]
Issue when exporting to preview website. 
<img width="418" alt="screen shot 2017-09-07 at 12 30 27" src="https://user-images.githubusercontent.com/25480086/30161589-1cd966d0-93c9-11e7-83ef-2fad0c38b03f.png">

**Comment by orarbel** [comment]
Hi @AllyHancock, Would it be possible to send us a sample file that fails to support@animaapp.com ?
